<section class="copyright">
$if(page.property_is.("project.license").("Apache-2.0"))$
    <div>$page.properties.("project.name")$ is Open Source and available under the Apache 2 License.</div>
$endif$
    <p class="legal">
        &copy; 2019-$page.properties.("date.year")$ <a href="https://akka-fusion.github.com/" target="_blank">Akka Fusion</a> |
        <a href="https://akka-fusion.github.io/fusion-discoveryx/" target="_blank">Fusion DiscoveryX</a> |
        <a href="https://akka-fusion.github.io/fusion-schedulerx/" target="_blank">Fusion SchedulerX</a>
    </p>
</section>

